lanuage: python
matrix:
  include:
    - name: "Python 3.7.1 on Linux"
      python: 3.7.1
      language: python
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install: export AMULET_NBT_VERSION=$TRAVIS_TAG

install:
  - pip3 install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user --upgrade setuptools wheel ; else pip3 install --upgrade setuptools wheel ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user -r requirements.txt ; else pip3 install -r requirements.txt ; fi
  - python3 setup.py bdist_wheel || python setup.py bdist_wheel
  - python3 setup.py install || python setup.py install

script:
  - python3 tests/nbt_tests.py || python tests/nbt_tests.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: "Amulet NBT $TRAVIS_TAG"
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: dist/*
  draft: true
  on:
    branch: master
    tags: true