lanuage: python
matrix:
  include:
    - name: "Python 3.7.1 on Linux"
      python: 3.7.1
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install --user --upgrade setuptools wheel
  - pip3 install --user -r requirements.txt
  - python3 setup.py bdist_wheel || python setup.py bdist_wheel

script:
  - python3 tests/nbt_tests.py || python tests/nbt_tests.py