## This file is generated from a template.
## Do not modify this file directly or your changes will get overwritten.
## Edit the accompanying .pyx.tp file instead.
## This file is generated by tempita. Do not modify this file directly or your changes will get overwritten.
## To edit this file edit the template in template/src

from typing import Any

from amulet_nbt._tag._cpp cimport TagNode, CByteTag, CShortTag, CIntTag, CLongTag
from .numeric cimport AbstractBaseNumericTag
# from amulet_nbt._const cimport ID_BYTE, ID_SHORT, ID_INT, ID_LONG
# from amulet_nbt._dtype import EncoderType


cdef class AbstractBaseIntTag(AbstractBaseNumericTag):
    """Abstract Base Class for all int Tag classes"""

    @property
    def py_int(self) -> int:
        """
        A python int representation of the class.
        The returned data is immutable so changes will not mirror the instance.
        """
        raise NotImplementedError

    @property
    def py_data(self) -> Any:
        return self.py_int


cdef class ByteTag(AbstractBaseIntTag):
    """
    A 1 byte integer class.
    Can Store numbers between -(2^7) and (2^7 - 1)
    """
    tag_id: int = 1

    def __init__(self, value = 0):
        value = int(value)
        self.cpp = (value & 0x7F) - (value & 0x80)

    @staticmethod
    cdef ByteTag wrap(CByteTag cpp):
        cdef ByteTag tag = ByteTag.__new__(ByteTag)
        tag.cpp = cpp
        return tag

    cdef TagNode to_node(self):
        cdef TagNode node
        node.emplace[CByteTag](self.cpp)
        return node

    @property
    def py_int(self) -> int:
        """
        A python int representation of the class.
        The returned data is immutable so changes will not mirror the instance.
        """
        return self.cpp

    def __eq__(self, other):
        if not isinstance(other, ByteTag):
            return NotImplemented
        cdef ByteTag other_ = other
        return self.cpp == other_.cpp

    def __repr__(self):
        return f"ByteTag({self.cpp})"

    def __str__(self):
        return str(self.cpp)

    def __reduce__(self):
        return ByteTag, (self.cpp,)

    def __copy__(self):
        return ByteTag.wrap(self.cpp)

    def __deepcopy__(self, memo=None):
        return ByteTag.wrap(self.cpp)

    def __hash__(self):
        return hash((1, self.cpp))

    def __int__(self):
        return int(self.cpp)

    def __float__(self):
        return float(self.cpp)

    def __bool__(self):
        return bool(self.cpp)

    def __ge__(self, other):
        if not isinstance(other, ByteTag):
            return NotImplemented
        cdef ByteTag other_ = other
        return self.cpp >= other_.cpp

    def __gt__(self, other):
        if not isinstance(other, ByteTag):
            return NotImplemented
        cdef ByteTag other_ = other
        return self.cpp > other_.cpp

    def __le__(self, other):
        if not isinstance(other, ByteTag):
            return NotImplemented
        cdef ByteTag other_ = other
        return self.cpp <= other_.cpp

    def __lt__(self, other):
        if not isinstance(other, ByteTag):
            return NotImplemented
        cdef ByteTag other_ = other
        return self.cpp < other_.cpp


cdef class ShortTag(AbstractBaseIntTag):
    """
    A 2 byte integer class.
    Can Store numbers between -(2^15) and (2^15 - 1)
    """
    tag_id: int = 2

    def __init__(self, value = 0):
        value = int(value)
        self.cpp = (value & 0x7FFF) - (value & 0x8000)

    @staticmethod
    cdef ShortTag wrap(CShortTag cpp):
        cdef ShortTag tag = ShortTag.__new__(ShortTag)
        tag.cpp = cpp
        return tag

    cdef TagNode to_node(self):
        cdef TagNode node
        node.emplace[CShortTag](self.cpp)
        return node

    @property
    def py_int(self) -> int:
        """
        A python int representation of the class.
        The returned data is immutable so changes will not mirror the instance.
        """
        return self.cpp

    def __eq__(self, other):
        if not isinstance(other, ShortTag):
            return NotImplemented
        cdef ShortTag other_ = other
        return self.cpp == other_.cpp

    def __repr__(self):
        return f"ShortTag({self.cpp})"

    def __str__(self):
        return str(self.cpp)

    def __reduce__(self):
        return ShortTag, (self.cpp,)

    def __copy__(self):
        return ShortTag.wrap(self.cpp)

    def __deepcopy__(self, memo=None):
        return ShortTag.wrap(self.cpp)

    def __hash__(self):
        return hash((2, self.cpp))

    def __int__(self):
        return int(self.cpp)

    def __float__(self):
        return float(self.cpp)

    def __bool__(self):
        return bool(self.cpp)

    def __ge__(self, other):
        if not isinstance(other, ShortTag):
            return NotImplemented
        cdef ShortTag other_ = other
        return self.cpp >= other_.cpp

    def __gt__(self, other):
        if not isinstance(other, ShortTag):
            return NotImplemented
        cdef ShortTag other_ = other
        return self.cpp > other_.cpp

    def __le__(self, other):
        if not isinstance(other, ShortTag):
            return NotImplemented
        cdef ShortTag other_ = other
        return self.cpp <= other_.cpp

    def __lt__(self, other):
        if not isinstance(other, ShortTag):
            return NotImplemented
        cdef ShortTag other_ = other
        return self.cpp < other_.cpp


cdef class IntTag(AbstractBaseIntTag):
    """
    A 4 byte integer class.
    Can Store numbers between -(2^31) and (2^31 - 1)
    """
    tag_id: int = 3

    def __init__(self, value = 0):
        value = int(value)
        self.cpp = (value & 0x7FFF_FFFF) - (value & 0x8000_0000)

    @staticmethod
    cdef IntTag wrap(CIntTag cpp):
        cdef IntTag tag = IntTag.__new__(IntTag)
        tag.cpp = cpp
        return tag

    cdef TagNode to_node(self):
        cdef TagNode node
        node.emplace[CIntTag](self.cpp)
        return node

    @property
    def py_int(self) -> int:
        """
        A python int representation of the class.
        The returned data is immutable so changes will not mirror the instance.
        """
        return self.cpp

    def __eq__(self, other):
        if not isinstance(other, IntTag):
            return NotImplemented
        cdef IntTag other_ = other
        return self.cpp == other_.cpp

    def __repr__(self):
        return f"IntTag({self.cpp})"

    def __str__(self):
        return str(self.cpp)

    def __reduce__(self):
        return IntTag, (self.cpp,)

    def __copy__(self):
        return IntTag.wrap(self.cpp)

    def __deepcopy__(self, memo=None):
        return IntTag.wrap(self.cpp)

    def __hash__(self):
        return hash((3, self.cpp))

    def __int__(self):
        return int(self.cpp)

    def __float__(self):
        return float(self.cpp)

    def __bool__(self):
        return bool(self.cpp)

    def __ge__(self, other):
        if not isinstance(other, IntTag):
            return NotImplemented
        cdef IntTag other_ = other
        return self.cpp >= other_.cpp

    def __gt__(self, other):
        if not isinstance(other, IntTag):
            return NotImplemented
        cdef IntTag other_ = other
        return self.cpp > other_.cpp

    def __le__(self, other):
        if not isinstance(other, IntTag):
            return NotImplemented
        cdef IntTag other_ = other
        return self.cpp <= other_.cpp

    def __lt__(self, other):
        if not isinstance(other, IntTag):
            return NotImplemented
        cdef IntTag other_ = other
        return self.cpp < other_.cpp


cdef class LongTag(AbstractBaseIntTag):
    """
    An 8 byte integer class.
    Can Store numbers between -(2^63) and (2^63 - 1)
    """
    tag_id: int = 4

    def __init__(self, value = 0):
        value = int(value)
        self.cpp = (value & 0x7FFF_FFFF_FFFF_FFFF) - (value & 0x8000_0000_0000_0000)

    @staticmethod
    cdef LongTag wrap(CLongTag cpp):
        cdef LongTag tag = LongTag.__new__(LongTag)
        tag.cpp = cpp
        return tag

    cdef TagNode to_node(self):
        cdef TagNode node
        node.emplace[CLongTag](self.cpp)
        return node

    @property
    def py_int(self) -> int:
        """
        A python int representation of the class.
        The returned data is immutable so changes will not mirror the instance.
        """
        return self.cpp

    def __eq__(self, other):
        if not isinstance(other, LongTag):
            return NotImplemented
        cdef LongTag other_ = other
        return self.cpp == other_.cpp

    def __repr__(self):
        return f"LongTag({self.cpp})"

    def __str__(self):
        return str(self.cpp)

    def __reduce__(self):
        return LongTag, (self.cpp,)

    def __copy__(self):
        return LongTag.wrap(self.cpp)

    def __deepcopy__(self, memo=None):
        return LongTag.wrap(self.cpp)

    def __hash__(self):
        return hash((4, self.cpp))

    def __int__(self):
        return int(self.cpp)

    def __float__(self):
        return float(self.cpp)

    def __bool__(self):
        return bool(self.cpp)

    def __ge__(self, other):
        if not isinstance(other, LongTag):
            return NotImplemented
        cdef LongTag other_ = other
        return self.cpp >= other_.cpp

    def __gt__(self, other):
        if not isinstance(other, LongTag):
            return NotImplemented
        cdef LongTag other_ = other
        return self.cpp > other_.cpp

    def __le__(self, other):
        if not isinstance(other, LongTag):
            return NotImplemented
        cdef LongTag other_ = other
        return self.cpp <= other_.cpp

    def __lt__(self, other):
        if not isinstance(other, LongTag):
            return NotImplemented
        cdef LongTag other_ = other
        return self.cpp < other_.cpp
