from ._value import BaseMutableTag

class BaseArrayTag(BaseMutableTag):
    def __init__(self, value=()): ...

class ByteArrayTag(BaseArrayTag): ...
class IntArrayTag(BaseArrayTag): ...
class LongArrayTag(BaseArrayTag): ...
