from typing import SupportsFloat
from ._numeric import BaseNumericTag

class BaseFloatTag(BaseNumericTag):
    def __init__(self, value: SupportsFloat): ...
    @property
    def py_float(self) -> float: ...

class FloatTag(BaseFloatTag): ...
class DoubleTag(BaseFloatTag): ...
