from typing import SupportsInt
from ._numeric import BaseNumericTag

class BaseIntTag(BaseNumericTag):
    def __init__(self, value: SupportsInt): ...
    @property
    def py_int(self) -> int: ...

class ByteTag(BaseIntTag): ...
class ShortTag(BaseIntTag): ...
class IntTag(BaseIntTag): ...
class LongTag(BaseIntTag): ...
