from ._numeric import BaseNumericTag

class BaseIntTag(BaseNumericTag):
    pass

class ByteTag(BaseIntTag): ...
class ShortTag(BaseIntTag): ...
class IntTag(BaseIntTag): ...
class LongTag(BaseIntTag): ...
