import numpy
from .value import BaseMutableTag

class BaseArrayTag(BaseMutableTag, numpy.ndarray):
    def __init__(self, value=()): ...

class TAG_Byte_Array(BaseArrayTag): ...
class TAG_Int_Array(BaseArrayTag): ...
class TAG_Long_Array(BaseArrayTag): ...
