from io import BytesIO
from typing import Iterator, Any, KeysView, ValuesView, ItemsView, Optional, Tuple

from .value import BaseMutableTag
from .util import BufferContext
from .dtype import AnyNBT

class TAG_Compound(BaseMutableTag):
    tag_id: int
    def __init__(self, value: Any = (), **kwvals: AnyNBT): ...
    @staticmethod
    def fromkeys(keys, value=None) -> TAG_Compound: ...
    @property
    def value(self) -> dict: ...
    def write_payload(self, buffer: BytesIO, little_endian: bool) -> None: ...
    @staticmethod
    def read_payload(buffer: BufferContext, little_endian: bool) -> TAG_Compound: ...
    def __eq__(self, other) -> bool: ...
    def strict_equals(self, other) -> bool: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> AnyNBT: ...
    def __setitem__(self, key: str, value: AnyNBT) -> None: ...
    def setdefault(self, key: str, value: AnyNBT): ...
    def update(self, other: Any = (), **others: AnyNBT): ...
    def __delitem__(self, key: str): ...
    def __iter__(self) -> Iterator[AnyNBT]: ...
    def __contains__(self, key: Any) -> bool: ...
    def __len__(self) -> int: ...
    def __reversed__(self): ...
    def clear(self) -> None: ...
    def get(self, key: str, default: Optional[AnyNBT] = None) -> Optional[AnyNBT]: ...
    def keys(self) -> KeysView: ...
    def values(self) -> ValuesView: ...
    def items(self) -> ItemsView: ...
    def pop(self, key: str, default: Optional[AnyNBT] = None) -> Optional[AnyNBT]: ...
    def popitem(self) -> Tuple[str, AnyNBT]: ...
