name: Stylecheck

on:
  push:
    branches:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install black cython~=3.0 numpy~=1.17

    - name: Run Stylecheck
      run: |
        python -m black --check --diff .
        python -m template check
