name: Unittests

on:
  push:
    branches:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025, python-version: '3.11', architecture: x64 }
          - { os: windows-2025, python-version: '3.12', architecture: x64 }
          - { os: windows-11-arm, python-version: '3.11', architecture: arm64 }
          - { os: windows-11-arm, python-version: '3.12', architecture: arm64 }
          - { os: macos-15-intel, python-version: '3.11', architecture: x64 }
          - { os: macos-15-intel, python-version: '3.12', architecture: x64 }
          - { os: macos-15, python-version: '3.11', architecture: arm64 }
          - { os: macos-15, python-version: '3.12', architecture: arm64 }
          - { os: ubuntu-24.04, python-version: '3.11', architecture: x64 }
          - { os: ubuntu-24.04, python-version: '3.12', architecture: x64 }

    runs-on: ${{ matrix.cfg.os }}
    timeout-minutes: 45

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Setup MSVC
      if: matrix.cfg.os == 'windows-11-arm'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64

    - name: Build
      run: |
        pip install .

    - name: Test with unittest
      run: python -m unittest discover -v -s tests
