name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025, python-version: '3.14', architecture: x64 }
          - { os: windows-11-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }

    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install build twine

    - name: Build
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_NBT_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
